ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS instagram text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS facebook text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS youtube text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS tiktok text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS linkedin text DEFAULT NULL;